### ISSUE TITLE
Eigen: Affine vs. Isometry

### ISSUE THREAD

**Issue by skasperski** [ros/geometry#101]
Why are *eigenToTF-functions using Eigen::Affine to represent tf::Transformation instead of Eigen::Isometry? Isn't the latter one correct to describe translation+rotation in 3D? Eigen explicitly prohibits conversion from affine to isometry:

```
// prevent conversions as:
// Isometry = Affine | AffineCompact
EIGEN_STATIC_ASSERT(EIGEN_IMPLIES(OtherMode==int(Affine)||OtherMode==int(AffineCompact), Mode!=int(Isometry)),
                    YOU_PERFORMED_AN_INVALID_TRANSFORMATION_CONVERSION)
```

So I ask myself if I can somehow still convert it, or if I also should use Affine to represent 3D-Transformations, which doesn't seem right to me.

Best regards,
Sebastian

**Comment by tfoote** [comment]
I believe that is a legacy of the port from Eigen2 to Eigen3: http://eigen.tuxfamily.org/dox/Eigen2ToEigen3.html

The recommendation was for `Transform3f` to go to `Affine3f` or `Projective3f` 

The transform is an isometry that would be a reasonable choice. Changing it at this point would require a lot of testing to verify we won't break current users.

**Comment by de-vri-es** [comment]
Pull request #113 would fix this.

**Comment by skasperski** [comment]
Yes, thanks for clarification and fix!
