### ISSUE TITLE
tf package: listener.py uses load_manifest?

### ISSUE THREAD

**Issue by mehwang** [ros/geometry#104]
@tfoote:
I've run into some errors with TF related to listener.py, and @mikeferguson has determined that it's related to a `roslib.load_manifest(PKG)` call.

We were wondering: is there a particular reason as to why it loads a manifest?

**Comment by tfoote** [comment]
It's no longer necessary. It's only there because no one has cleared it out. A pr to remove it would be appreciated.

**Comment by mehwang** [comment]
I've made a PR to remove all the load_manifests I could find.

**Comment by mehwang** [comment]
@mikeferguson also requests that this be tagged into a release ASAP so we can push the changes to our side.

**Comment by tfoote** [comment]
I'll try to get a release out next week.

**Comment by mikeferguson** [comment]
Thanks Tully!
