### ISSUE TITLE
getParent() - Feature Request (Python API)

### ISSUE THREAD

**Issue by theNerd247** [ros/geometry#106]
I noticed the python API doesn't have `getParent()` found in the C++ `tf::Transform::getParent()`. In general it would make sense to provide the functionality to allow users to get the parent frame of a given frame - since tf already assumes each node in the frame tree can only have one parent.

**Comment by tfoote** [comment]
In python you can access the contents of the datatype. Is there a reason you need a method?

**Comment by tfoote** [comment]
Since the api would be redundant with direct access I'm going to close this as won't fix.
