### ISSUE TITLE
tf::assertQuaternionValid do not complain on NaN quaternion values

### ISSUE THREAD

**Issue by corot** [ros/geometry#107]
[tf::assertQuaternionValid](https://github.com/ros/geometry/blob/indigo-devel/tf/include/tf/tf.h#L393) do not complain on nan quaternion values, what for me is strange. But if it is just an accepted convention, please discard this issue.

**Comment by tfoote** [comment]
it's only doing range checking, not nan checking. It would be reasonable to extend it to do nan checking. A pull request would be appreciated.
