### ISSUE TITLE
Is arguments of lookupTransform opposite?

### ISSUE THREAD

**Issue by garaemon** [ros/geometry#108]
tf document and header says:

``` c++
void Transformer::lookupTransform(const std::string& target_frame, 
                                           const std::string& source_frame,
                                           const ros::Time& time, StampedTransform& transform) const
```

But in tf_echo, the order looks opposite.
https://github.com/ros/geometry/blob/indigo-devel/tf/src/tf_echo.cpp#L107

``` c++
echoListener.tf.lookupTransform(source_frameid, target_frameid, ros::Time(), echo_transform);
```

cc: @wkentaro

**Comment by wkentaro** [comment]
I have tested the `lookupTransform` with rviz and `static_transform_publisher` below, and I think these are target/source_frame are opposite.
https://github.com/jsk-ros-pkg/jsk_recognition/pull/1274

![image](https://cloud.githubusercontent.com/assets/4310419/10672704/bcb5d382-792c-11e5-83d9-955d1a986579.png)

**Comment by tfoote** [comment]
It depends on if your referring to the transform of the coordinate or a point between the coordinate frames. 

`tf_echo` and the broadcasters are focused on the transforms between the coordinate frames. When you're building the tree that is what you want to pay attention to. 

When you're using the tf tree you care about transforming data. `lookupTransform` is looking up the transform for an object in the source frame, into the target frame. Which is the inverse of the transform of the coordinate frames that tf_echo would report or that you would publish.

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/nomenclature-of-tf-echo-and-tf-listener/36985/7
