### ISSUE TITLE
view_frames Fails to Parse Version of Non-Standard Graphviz

### ISSUE THREAD

**Issue by evenator** [ros/geometry#114]
I have graphviz installed from the [development ppa](https://launchpad.net/~gviz-adm/+archive/ubuntu/graphviz-dev). When I run `dot -V`, the result is

```
dot - graphviz version 2.39.20151030.1804 (20151030.1804)
```

The existing version extraction regex extracts `2.39.20151030.1804` as the version number, which is not a valid distutils version string because it has too many digit groups. I was able to fix the problem by changing the regex on line 94 of view_frames to `".*version (\d+\.?\d*)"`, which only extracts the first two digit groups of the version string.

**Comment by trigal** [comment]
==================
Inviata da dispositivo mobile
**Sent from mobile phone**

Augusto Luis Ballardini, PhD Student
trigal@gmail.com or
ballardini@disco.unimib.it
Mobile phone: +393394705558


-----Original Message-----
