### ISSUE TITLE
TF: how to manage similarity transformation

### ISSUE THREAD

**Issue by winf** [ros/geometry#121]
Recently I am doing some Monocular SLAM homework under the framework of ROS.
The transformation from camera world to real world is a similarity transform,but TF in ROS means rigid body transformation.
Since whether  scale was fixed or not is  the  only difference between similarity transformation and rigid body transformation.
Is it possible still using TF to mange similarity transformation,and how ?

**Comment by tfoote** [comment]
tf is not designed for anything but ridged transforms. If you'd like to explore adding support I think you could reuse the tree structure and the lower level data storage APIs but the higher level APIs would be less reuseable. This isn't something we're going to target for development so I'm going to close this issue.
