### ISSUE TITLE
view_frames doesn't show frames published on /tf_static

### ISSUE THREAD

**Issue by rhaschke** [ros/geometry#123]
Using `static_transform_publisher` from `tf2`, fixed transformations are published on `/tf_static` instead of `/tf`. These frames are not displayed by `view_frames`. Is there a proper replacement in tf2? Or should `view_frames` be fixed here?

**Comment by tfoote** [comment]
There's a new tool in `tf2_tools` `view_frames.py`

**Comment by rhaschke** [comment]
Thanks. Missed that package during installation..
