### ISSUE TITLE
Angles package not present??

### ISSUE THREAD

**Issue by t1jump** [ros/geometry#13]
Angles is not a resident package in the geometry metapackage, but the geometry package.xml has the line

<run_depend>angles</run_depend>

so upon running rosdep it throws and error, "Unable to locate package ros-groovy-angles.

**Comment by tfoote** [comment]
angles is a dependency of multiple packages in the geometry repo.  It either needs to be in your source workspace or installed on your system.

**Comment by t1jump** [comment]
So "angles" should be added direct to source... Thanks!!
