### ISSUE TITLE
tf::Transformer::setTransform should have a parameter for is_static

### ISSUE THREAD

**Issue by mithunjacob** [ros/geometry#135]
tf::Transformer::setTransform calls tf2::BufferCore::setTransform which takes is_static as a parameter. The is_static parameter for tf::Transformer::setTransform can be passed on to tf2::BufferCore::setTransform.

**Comment by tfoote** [comment]
The concept of a static transform was added in tf2. The tf API is deprecated and maintained for stability. We won't target enhancements for it.
