### ISSUE TITLE
Transform PoseWithCovarianceStamped

### ISSUE THREAD

**Issue by RobertBlakeAnderson** [ros/geometry#158]
Is there any interest in adding a function to transform PoseWithCovarianceStamped messages? If so, I have some code that could become a pull request to this effect.

**Comment by tfoote** [comment]
I'd rather not extend the support here in geometry but would be interested in adding support for it in tf2_geometry_msgs following this tutorial: http://wiki.ros.org/tf2/Tutorials/Create%20Data%20Conversion%20Package%20%28C%2B%2B%29

**Comment by RobertBlakeAnderson** [comment]
Alright, I'll look into that.
