### ISSUE TITLE
roswtf reports "WARNING The following node subscriptions are unconnected" to "/tf_static"

### ISSUE THREAD

**Issue by 130s** [ros/geometry#165]
```
WARNING The following node subscriptions are unconnected:
 * /turtle_pointer:
   * /tf_static
```
This warning may or may not be so frequently observed but I found it confusing while it's probably not harmful for the most of the times. Some question threads [1]( https://answers.ros.org/question/115591/tf_static-and-nodelet_manager-unconnected-for-my-kinects/), [2](https://answers.ros.org/question/115591/tf_static-and-nodelet_manager-unconnected-for-my-kinects/).

Looks like this is printed purely in graph parsing done in `roswtf`, not anywhere in tf, but I'd like to ask here if we can improve the warning message.

**Comment by tfoote** [comment]
There's nothing geometry package related in this warning or connection issue. This has to do with the subscriber list for the topic being different than the master. It can be caused by an unclean shutdown where the publisher didn't unregister with the master I believe.
