### ISSUE TITLE
casting away const qualifier in Vector3

### ISSUE THREAD

**Issue by C-NR** [ros/geometry#170]
In the current release of ROS Kinetic Kame delivered by i.e. Ubuntu exists an issue with casting away const in the include/tf/LinearMath/Vector3.h > tfSwapScalarEndian  method.

Line 626  must be changed in the according Vector3.h from:
unsigned char* src = (unsigned char*) &sourceVal;
to:
const unsigned char* src = (const unsigned char*) &sourceVal;
in to not casrt away the const qualifier.

**Comment by tfoote** [comment]
Fixed in #167
