### ISSUE TITLE
Must I sendTransform constantly even if the transform does not change?

### ISSUE THREAD

**Issue by hyansuper** [ros/geometry#190]
I can specify the joint_state_publisher node to subscribe to a source_list so that it republishes my joint state msg. Can I do the same with robot_state_publisher node?

I mean, can I use TransformBroadcaster.sendTransform(...) occasionally when a peticular transform updates, without having to send the transform all the time even if it does not change?
The static_transform_publisher node does not fit this scenario because it requires that the transform never change.

Thanks

**Comment by tfoote** [comment]
The tf system doesn't make assumptions about future values of transforms. If you say what the transform values is at t=1 and t=3 it cannot tell you about what the values is at t=4 until it hears about a value at t>=4

It will do interpolation between values but not try to extrapolate into the future. If you have more questions please ask on answers.ros.org
