### ISSUE TITLE
Unable to use tf_conversions inside anaconda enviroment

### ISSUE THREAD

**Issue by rickstaa** [ros/geometry#198]
I try to use tf_conversions inside a anaconda enviroment. But when I try to import it I get the following error:

```
>>> import tf_conversions
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/ros/melodic/lib/python2.7/dist-packages/tf_conversions/__init__.py", line 30, in <module>
    from .posemath import *
  File "/opt/ros/melodic/lib/python2.7/dist-packages/tf_conversions/posemath.py", line 34, in <module>
    from PyKDL import *
```

This might be a consequence of anaconda [not playing well with ROS](https://answers.ros.org/question/256886/conflict-anaconda-vs-ros-catking_pkg-not-found/) but I just wanted to check if there is an easy solution.

**Comment by tfoote** [comment]
You'll need to document how you "used" tf_conversions inside the anaconda environment. It looks like you're missing the pykdl implementation which is a compiled library that using SIP. I suspect if you install that library into your anaconda environment you'll this will work. If you need more help please ask on answers.ros.org and make sure to provide enough information to reproduce your problem.
