### ISSUE TITLE
The Euler Angles sequence in tf_echo

### ISSUE THREAD

**Issue by Allenhanbo** [ros/geometry#200]
Hi all, I am using tf_echo to echo my two moving drone's position. I would like to know, in the results of tf_echo, what the sequence of RPY? Is it the sequence of Raw and then Pitch and the last is Yaw?

**Comment by tfoote** [comment]
Please ask questions on http://answers.ros.org according to our support policy: http://wiki.ros.org/Support We try to keep the issue tracker reserved for bugs and feature developments.
