### ISSUE TITLE
Improvement about Euler angles order?

### ISSUE THREAD

**Issue by Julien-Livet** [ros/geometry#231]
In my current project, I noticed a mistake that I do: I believed that the Euler angles order of URDF (rpy="...") was the same that "rosrun tf static_transform_publisher" with paste/copy. I don't know if other people meet this trick, for potential improvement...

https://github.com/ros/geometry/blob/d51887c976a45ba01db9c61361e94076d3bcf3f1/tf/src/static_transform_publisher.cpp

**Comment by peci1** [comment]
Changing the order of angles is not possible for released ROS 1 distros. As there will be no more ROS 1 distros, I suggest closing this issue.

You always have to read to docs before using a tool (altough I agree it'd be ideal to have the order of arguments identical in all tools).
