### ISSUE TITLE
Undefined symbol during link of tf_conversions

### ISSUE THREAD

**Issue by tlau** [ros/geometry#45]
Doing a build from source against today's version of tf_conversions, I'm getting this linker error:

```
Scanning dependencies of target tf_conversions
[ 50%] [100%] Building CXX object CMakeFiles/tf_conversions.dir/src/tf_kdl.cpp.o
Building CXX object CMakeFiles/tf_conversions.dir/src/tf_eigen.cpp.o
Linking CXX shared library /Users/tlau/ros/devel_isolated/tf_conversions/lib/libtf_conversions.dylib
Undefined symbols for architecture x86_64:
  "KDL::Vector::Normalize(double)", referenced from:
      KDL::Rot(KDL::Vector const&) in tf_kdl.cpp.o
  "KDL::Rotation::Quaternion(double, double, double, double)", referenced from:
      tf::quaternionTFToKDL(tf::Quaternion const&, KDL::Rotation&) in tf_kdl.cpp.o
  "KDL::operator*(KDL::Rotation const&, KDL::Rotation const&)", referenced from:
      KDL::operator*(KDL::Frame const&, KDL::Frame const&) in tf_kdl.cpp.o
      KDL::addDelta(KDL::Rotation const&, KDL::Vector const&, double) in tf_kdl.cpp.o
  "KDL::Rotation::GetQuaternion(double&, double&, double&, double&) const", referenced from:
      tf::quaternionKDLToTF(KDL::Rotation const&, tf::Quaternion&) in tf_kdl.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [/Users/tlau/ros/devel_isolated/tf_conversions/lib/libtf_conversions.dylib] Error 1
make[1]: *** [CMakeFiles/tf_conversions.dir/all] Error 2
make: *** [all] Error 2
<== Failed to process package 'tf_conversions': 
  Command '/opt/ros/hydro/env.sh make -j4 -l4' returned non-zero exit status 2
```

I'm building according to [hydro installation instructions](http://wiki.ros.org/hydro/Installation/OSX/Homebrew/Source) on Mac OSX.

Any ideas?

**Comment by chradja** [comment]
Same issue here i'm also stuck there on mac os X 10.8.5

**Comment by chradja** [comment]
Here is my stack trace : 
Undefined symbols for architecture x86_64:
  "KDL::Vector::Normalize(double)", referenced from:
      KDL::Rot(KDL::Vector const&) in tf_kdl.cpp.o
  "KDL::Rotation::Quaternion(double, double, double, double)", referenced from:
      tf::quaternionTFToKDL(tf::Quaternion const&, KDL::Rotation&) in tf_kdl.cpp.o
  "KDL::operator_(KDL::Rotation const&, KDL::Rotation const&)", referenced from:
      KDL::operator_(KDL::Frame const&, KDL::Frame const&) in tf_kdl.cpp.o
      KDL::addDelta(KDL::Rotation const&, KDL::Vector const&, double) in tf_kdl.cpp.o
  "KDL::Rotation::GetQuaternion(double&, double&, double&, double&) const", referenced from:
      tf::quaternionKDLToTF(KDL::Rotation const&, tf::Quaternion&) in tf_kdl.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: **\* [/Users/chradja/ros_catkin_ws/devel_isolated/tf_conversions/lib/libtf_conversions.dylib] Error 1
make[1]: **\* [CMakeFiles/tf_conversions.dir/all] Error 2
make: **\* [all] Error 2

**Comment by chradja** [comment]
I found out why in fact there is missing (in my case) this path to library : /Users/chradja/ros_catkin_ws/install_isolated/lib/liborocos-kdl.dylib
But as I'm a little newbie in cmake, etc, I have no idea where to put it (instead of in the c++ commande generated).

**Comment by chradja** [comment]
here is the c++ command to launch from folder : /Users/chradja/ros_catkin_ws/build_isolated/tf_conversions
After that you can continue the install process (replace /Users/chadja with your own prefix) 

/usr/bin/c++   -dynamiclib -Wl,-headerpad_max_install_names   -o /Users/chradja/ros_catkin_ws/devel_isolated/tf_conversions/lib/libtf_conversions.dylib -install_name /Users/chradja/ros_catkin_ws/devel_isolated/tf_conversions/lib/libtf_conversions.dylib CMakeFiles/tf_conversions.dir/src/tf_kdl.cpp.o CMakeFiles/tf_conversions.dir/src/tf_eigen.cpp.o  -L/Users/chradja/ros_catkin_ws/install_isolated/lib /Users/chradja/ros_catkin_ws/install_isolated/lib/libcpp_common.dylib /Users/chradja/ros_catkin_ws/install_isolated/lib/libroscpp_serialization.dylib /Users/chradja/ros_catkin_ws/install_isolated/lib/librostime.dylib /usr/local/lib/libboost_date_time-mt.dylib /usr/local/lib/libboost_system-mt.dylib /usr/local/lib/libboost_thread-mt.dylib /Users/chradja/ros_catkin_ws/install_isolated/lib/libkdl_conversions.dylib /Users/chradja/ros_catkin_ws/install_isolated/lib/liborocos-kdl.dylib /Users/chradja/ros_catkin_ws/install_isolated/lib/libtf.dylib /Users/chradja/ros_catkin_ws/install_isolated/lib/libmessage_filters.dylib /Users/chradja/ros_catkin_ws/install_isolated/lib/libroscpp.dylib /usr/local/lib/libboost_signals-mt.dylib /usr/local/lib/libboost_filesystem-mt.dylib /Users/chradja/ros_catkin_ws/install_isolated/lib/librosconsole.dylib /usr/local/lib/libboost_regex-mt.dylib /usr/local/lib/liblog4cxx.dylib /Users/chradja/ros_catkin_ws/install_isolated/lib/libxmlrpcpp.dylib /Users/chradja/ros_catkin_ws/install_isolated/lib/libtf2_ros.dylib /Users/chradja/ros_catkin_ws/install_isolated/lib/libactionlib.dylib /Users/chradja/ros_catkin_ws/install_isolated/lib/libtf2.dylib /Users/chradja/ros_catkin_ws/install_isolated/lib/libconsole_bridge.dylib -Wl,-rpath,/Users/chradja/ros_catkin_ws/install_isolated/lib

**Comment by chradja** [comment]
edit :: 
when I do again ./src/catkin/bin/catkin_make_isolated --install then error come back again.
I don"t know how to apply the fix above permanently enough to finish the build...

**Comment by chradja** [comment]
I finally succesfully build tf_conversions by changing this line in ~/ros_catkin_ws/src/tf_conversions/CMakeLists.txt :
from
target_link_libraries(${PROJECT_NAME} ${catkin_LIBRARIES})
to
target_link_libraries(${PROJECT_NAME} ${catkin_LIBRARIES} /Users/chradja/ros_catkin_ws/install_isolated/lib/liborocos-kdl.dylib)

then I delete the content of current built folder and launch again the install starting at failed package :
rm -rf /Users/chradja/ros_catkin_ws/build_isolated/tf_conversions/*
./src/catkin/bin/catkin_make_isolated --install --from-pkg tf_conversions

**Comment by tfoote** [comment]
This probably needs a patch similar to the robot_state_publisher one here:
https://github.com/ros/robot_state_publisher/commit/c8b1d0cce5f27c30f019d09fa991da5f6a7b038e

**Comment by tlau** [comment]
Yes, I patched it similar to the robot_state_publisher one and it worked. Where should I submit the patch?

**Comment by tfoote** [comment]
If you could submit a pull request against hydro-devel that would be great. but I can merge it in any form.
