### ISSUE TITLE
eigen_conversions package could be split to reduce dependency pollution

### ISSUE THREAD

**Issue by aleeper** [ros/geometry#56]
In a source-based project one may want to pull in the Eigen <--> Msg conversions utilities in `eigen_conversions` without needing to depend on `orocos_kdl`, which is a pretty big dependency.

I propose splitting this into two packages, perhaps `eigen_msg_conversions` and `eigen_kdl_conversions`. To preserve compatibility with existing code, the existing `eigen_conversions` package could have headers that just include the headers of the new separate packages.

Thoughts? I'd be willing to do this as a pull request once there is agreement on the spec.

**Comment by tfoote** [comment]
the tf2 convert methods is the cleaner way to do things. it looks like tf2_eigen as omitted. It would be best to implement the tf2_eigen package as a parallel to tf2_kdl, tf2_bullet, tf2_msg converter packages. The new technique decouples the dependencies using templates. 

http://wiki.ros.org/tf2/Tutorials/Migration/DataConversions

https://github.com/ros/geometry_experimental/blob/hydro-devel/tf2_kdl/include/tf2_kdl/tf2_kdl.h

You could also make a separate package for eigen-kdl direct converters if efficiency is at a premium, maybe tf2_eigen_kdl

**Comment by aleeper** [comment]
So, I see that this is rather nice. 
Is geometry_experimental going to be renamed at some point? When does it stop being experimental and become the "preferred" way to do things? (I suspect tf2 adoption might be slow because of this.)

**Comment by tfoote** [comment]
I will probably rename the repo at some point. It is recommended, and the
name's only reflected in the metapackage, I can't easily change the name
due to backwards compatibility.

**Comment by tfoote** [comment]
Closing as the tf2 solution is adaquate, and we don't want to spend the effort to upgrade a deprecated package.
