### ISSUE TITLE
tf.transformations.quaternion_from_matrix() is misleading

### ISSUE THREAD

**Issue by jbohren** [ros/geometry#64]
The `tf.transformations.quaternion_from_matrix()` function says it returns a quaternion from a rotation matrix, but it fails if you give it an actual rotation matrix (element of SO(3)). Instead it requires that the input "rotation matrix" is a 4x4 matrix (element of SE(3)).

If you try passing it a 3x3 rotation matrix, you get the following error:

```
  File "/opt/ros/hydro/lib/python2.7/dist-packages/tf/transformations.py", line 1206, in quaternion_from_matrix
    M = numpy.array(matrix, dtype=numpy.float64, copy=False)[:4, :4]
IndexError: too many indices
```

I understand the utility of extracting a quaternion directly from a rigid transform, but it should also accept an actual rotation matrix as input.

https://github.com/ros/geometry/blob/indigo-devel/tf/src/tf/transformations.py#L1196
Related to #49

**Comment by tfoote** [comment]
This is an external library pulled in for convenience. I don't want to diverge from it's API. We've had bad experiences with that in the past.

**Comment by jbohren** [comment]
> This is an external library pulled in for convenience. I don't want to diverge from it's API. We've had bad experiences with that in the past.

Alright, would a PR that fixes the documentation be welcomed?

**Comment by tfoote** [comment]
Definitely.

**Comment by tfoote** [comment]
Closing this as #49 would be adequate.
