### ISSUE TITLE
 Lookup would require extrapolation into the future despite waitForTransform 

### ISSUE THREAD

**Issue by pronobis** [ros/geometry#73]
I have the following code in a pointcloud callback

```
  listener_->waitForTransform(baseFrame_, msg->header.frame_id, msg->header.stamp, ros::Duration(10.0));

  // Convert
  pcl::PointCloud<pcl::PointXYZ> cloud;
  pcl::fromROSMsg(*msg, cloud);

  // Transform
  pcl::PointCloud<pcl::PointXYZ> cloudT;
  pcl_ros::transformPointCloud<pcl::PointXYZ>(baseFrame_, cloud, cloudT, *listener_);
```

and despite the waitfortransform being there, I get:

[ERROR] [/xtion_qqvga/depth/cliff_detector@transformPointCloud:149]: Lookup would require extrapolation into the future.  Requested time 1414987674.082394880 but the latest data is at time 1414987674.078320503, when looking up transform from frame [xtion_depth_optical_frame] to frame [base_link]

all the time. 

I have to say that I tried ros::Time(0) instead of the msg->stamp and also I tried using tf::MessageFilters with the same result. 

Interestingly, adding a fixed duration to the time makes the errors disappear, but is obviously not a solution.

I'm on Indigo.

**Comment by tfoote** [comment]
First you need to check the return code on the waitForTransform. Please check that the timestamps are getting converted correctly. Can you transform the unconverted cloud?

**Comment by tfoote** [comment]
Due to no response I'm assuming checking the return code fixed the problem. Please comment if not so and we can reopen.

**Comment by saurabhbansal90** [comment]
Hello Tully,

I am trying to create octomap with the robot I have. I am using ROS kinetic on Ubuntu16. So here I am not writing any code, but writing an yaml file to run the octomap plugin, as in this [tutorial](http://docs.ros.org/indigo/api/moveit_tutorials/html/doc/pr2_tutorials/planning/src/doc/perception_configuration.html).
Here I am facing same error:
`[ERROR] [1524044914.670571571, 708.496000000]: Transform error: Lookup would require extrapolation into the future.  Requested time 708.429000000 but the latest data is at time 708.400000000, when looking up transform from frame [gripper_roll_link] to frame [rgbd_camera_optical_frame]
[ERROR] [1524044914.670604581, 708.496000000]: Transform cache was not updated. Self-filtering may fail.`

Although octomap is visible in the rviz, but still I don't know the reason why this error is occurred.
Here is my  yaml file content:
`sensors:
    sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /rgbd_camera/rgb/points
    max_range: 5.0
    point_subsample: 1
    padding_offset: 0.1
    padding_scale: 1.0
    filtered_cloud_topic: filtered_cloud`
And I made the octomap frame to be "odom_combined"

Can somebody please let me know how can I avoid these errors.

With best regards,
Saurabh

**Comment by tfoote** [comment]
Please ask questions on http://answers.ros.org according to our support policy: http://wiki.ros.org/Support We try to keep the issue tracker reserved for bugs and feature developments.

Also when you ask please provide a minimal self contained example of how to reproduce the problem. Otherwise we'll be just guessing at your issue. Note the the error that you're quoting is common and has many causes.
