### ISSUE TITLE
getParent doesn't call strip_leading_slash

### ISSUE THREAD

**Issue by galou** [ros/geometry#74]
`waitForTransform` calls `"strip_leading_slash(target_frame)"`whereas `getParent` doesn't.

Shouldn't the behavior be consistent?

**Comment by galou** [comment]
Any comment on this issue? I'm ready to write a PR depending on what should be done.

**Comment by tfoote** [comment]
Yes, reviewing the two methods. When it transitions from tf into the tf2 methods it should be stripped in getParent like waitForTransform. Thanks in advance for the PR!

**Comment by galou** [comment]
cf. #79.

**Comment by galou** [comment]
Shouldn't a deprecation warning be thrown both in `waitForTransform` and `getParent`? Looking at #63. frameExists also doesn't strip the leading slash but the unittest with leading slash was explicitely commented out for frameExists.

**Comment by tfoote** [comment]
Fixed in #79
