### ISSUE TITLE
getRoll and getPitch

### ISSUE THREAD

**Issue by chipironcin** [ros/geometry#78]
Include getRoll and getPitch functions as getYaw is already implemented. For the sake of simplicity.

**Comment by tfoote** [comment]
That method is specifically provided as a helper for the 2d case. If you'd like full 3d methods please use the linear math libraries included with tf which is all this method does for you: https://github.com/ros/geometry/blob/bee989f3f4ab39e7ecf5c1bfe61d73d255b84c69/tf/include/tf/transform_datatypes.h#L131-L135 and throws away the pitch and roll. We don't want to duplicate the linear math API,
