### ISSUE TITLE
ros wiki view_frames information is wrong 

### ISSUE THREAD

**Issue by jihoonl** [ros/geometry#8]
http://www.ros.org/wiki/tf#view_frames

view_frames usage description groovy is out-dated

**Comment by hershwg** [comment]
This looks to me like a bug in the CMakeLists.txt of geometry/tf.  Here is what does the work in that file:

```
# Install rosrun-able scripts
install(PROGRAMS 
  scripts/bullet_migration_sed.py
  scripts/tf_remap
  scripts/view_frames
  DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION} )
```

Looking at an installed instance of groovy tf though, I see that bullet_migration_sed.py, tf_remap, and view_frames are all installed in /opt/ros/groovy/bin, which is NOT where "rosrun" finds things.

I don't know what is the proper catkin variable to send them to the directory /opt/ros/groovy/lib/tf, where tf_echo, tf_monitor, etc are all installed.

Those are installed via this section:

```
install(TARGETS ${PROJECT_NAME} tf_echo tf_empty_listener tf_change_notifier tf_monitor static_transform_publisher
  LIBRARY DESTINATION ${CATKIN_PACKAGE_LIB_DESTINATION}
  RUNTIME DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION})
```

...which seems to use the exact same catkin variable.  Is it the difference between TARGETS and PROGRAMS?

**Comment by hershwg** [comment]
Oops, looks like this has already been fixed.  The code I quoted above is from the fixed version, but it hasn't been released yet, which is why the files on my computer are still in the wrong place.  Here's the fix: https://github.com/ros/geometry/commit/87448c2ec46f5a6ce26e15c43bb3fe0a1b59f584

Closing this bug, as the fix will presumably be released soon.

**Comment by jihoonl** [comment]
@hershwg  Can we keep this open until new version get released?

**Comment by tfoote** [comment]
@jihoonl This ticket is closed appropriately.  Depending on the development mode you could open a ticket "release xyz version into groovy" as a reminder, where xyz is the next version. Or on a more active project you would use a milestone.

**Comment by jihoonl** [comment]
Alright. Thanks.
