### ISSUE TITLE
tf.Exception thrown while using waitForTransform when a frame doesn't exist

### ISSUE THREAD

**Issue by marcoesposito1988** [ros/geometry#93]
As reported by other users as well in http://answers.ros.org/question/207039/tfexception-thrown-while-using-waitfortransform a bug seems to have appeared.

waitForTransform throws a tf.Exception if one of the frames doesn't exist yet (which is actually the point of waitForTransform).

The bug appeared recently (after the end of March) but persists even with version 1.11.4, so it is likely NOT in TF. Any idea about the reason?

**Comment by marcoesposito1988** [comment]
It must be a bug in TF2. When I checked out geometry 1.11.4 the bug was still there, but when I also checked out geometry-experimental 0.5.7 the bug disappeared.

Closing here and opening on geometry-experimental.

**Comment by tfoote** [comment]
Ticket here: https://github.com/ros/geometry_experimental/issues/102

**Comment by tfoote** [comment]
Added unit test here: 9624370b2327480ee429c5671455e3880825d256
