### ISSUE TITLE
tf tutorials might be a requirement for URDF tutorials

### ISSUE THREAD

**Issue by 130s** [ros/geometry#94]
Originally I noticed in [this thread](http://answers.ros.org/question/207947/how-do-you-use-externally-defined-materials-in-a-urdfxacro-file/?answer=207952#post-id-207952).
- [ROS Tutorials](http://wiki.ros.org/ROS/Tutorials) enlists URDF earlier than TF.
- Under `urdf/Tutorials` pages, there's [no mention about tf being prerequisite](https://www.google.co.jp/search?client=ubuntu&channel=fs&q=site%3Aros.org%2Furdf%2FTutorials+tf&ie=utf-8&oe=utf-8&gfe_rd=cr&ei=jes9VaW2Es798we9tYCgDA).

I [added prerequisite section at the top of URDF tutorial page](http://wiki.ros.org/action/info/urdf/Tutorials?action=diff&rev2=17&rev1=16). I don't know whether this is sufficient.

**Comment by tfoote** [comment]
That looks like a good solution. I don't think there's anything to do here for this.
